# encoding: utf-8
svn: 
  - svn_path: svn
    url: "https://xsjreposvr7.seasungame.com/svn/FSM/trunk/MechaWar/Client/Projects/Runtime/Settings/Table"
    usr: "wangjiaojiao1"
    pwd: "wjflying0.ai"
  - svn_path: svn
    url: "svn://path/to/file"
    usr: ""
    pwd: ""
